import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import JSZip from 'jszip';
import type { Project, SitePage, SiteSection } from '../../../shared/project';
import { demoComponents, type ComponentDefinition } from '../../../shared/componentRegistry';
import { resolveSectionAssets } from '../../../shared/assetBinding';
import { validateProjectForExport } from '../../../shared/exportValidation';
import { getStudioComponent } from '../../../src/studio-components/resolver';
import { compileProjectDesignTokens } from '../../../src/studio-components/designTokenCompiler';
import {
  collectAndProcessExportAssets,
  rewriteAssetUrlsInHtml,
} from './exportAssetHelper';
import type {
  ExportResult,
  ExportManifest,
  SiteExporter,
} from '../../../shared/exportTypes';

const componentLookup = new Map<string, ComponentDefinition>(
  demoComponents.map((c) => [c.id, c])
);

export class WordPressThemeExporter implements SiteExporter {
  id = 'wordpress' as const;
  name = 'WordPress Block Theme';

  canExport(project: Project): boolean {
    return project.projectType === 'business_website';
  }

  async validate(project: Project) {
    return validateProjectForExport(project, 'wordpress');
  }

  async export(project: Project): Promise<ExportResult> {
    const validation = await this.validate(project);
    const generatedAt = new Date().toISOString();

    const safeSlug = (project.business.businessName || project.name || 'natanel-studio-site')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') || 'website';
    const filename = `${safeSlug}-wordpress-theme.zip`;

    // 1. Build Manifest
    const manifest: ExportManifest = {
      studioVersion: '1.0.0',
      generatedAt,
      projectId: project.id,
      projectName: project.name,
      businessName: project.business.businessName,
      target: 'wordpress',
      direction: project.business.direction,
      language: project.business.language || 'English',
      pages: (project.pages || []).map((p) => ({
        id: p.id,
        name: p.name,
        slug: p.slug,
        sectionCount: (p.sections || []).length,
        sections: (p.sections || []).map((s) => ({
          id: s.id,
          name: s.name,
          componentRegistryId: s.componentRegistryId,
        })),
      })),
      componentIdsUsed: Array.from(
        new Set(project.pages.flatMap((p) => p.sections.map((s) => s.componentRegistryId)))
      ),
      assetIdsUsed: Array.from(
        new Set(project.pages.flatMap((p) => p.sections.flatMap((s) => s.assetIds || [])))
      ),
      designTokenSummary: {
        themeMode: 'dark',
        primaryColor: project.designSystem?.colors?.[0] || '#111113',
        fontDisplay: project.designSystem?.typography || 'Editorial Serif',
        fontBody: 'Inter',
        density: project.brand.contentDensity || 'balanced',
      },
    };

    if (!validation.valid) {
      return {
        success: false,
        target: 'wordpress',
        filename,
        mimeType: 'application/zip',
        generatedAt,
        validation,
        manifest,
        message: `Validation failed with ${validation.errors.length} error(s).`,
      };
    }

    // 2. Process and collect used assets
    const { assets: processedAssets, urlToFilenameMap } = await collectAndProcessExportAssets(project);

    // 3. Compile design tokens
    const compiledTokens = compileProjectDesignTokens(project.designSystem, {
      industry: project.business.industry,
      themeMode: 'dark',
      density: project.brand.contentDensity,
      direction: project.business.direction,
    });

    const isRtl = project.business.direction === 'rtl';
    const themeName = project.business.businessName || project.name || 'Natanel Studio Theme';
    const themePrefix = safeSlug.replace(/-/g, '_');

    // 4. Initialize ZIP container
    const zip = new JSZip();

    // style.css
    const styleCss = `/*
Theme Name: ${themeName}
Theme URI: https://natanel.studio
Author: Natanel Studio
Author URI: https://natanel.studio
Description: Modern WordPress block theme generated by Natanel Studio for ${themeName}. Site Editor compatible, zero plugin dependencies.
Version: 1.0.0
Requires at least: 6.2
Tested up to: 6.7
Requires PHP: 7.4
Text Domain: ${safeSlug}
*/
`;
    zip.file('style.css', styleCss);

    // theme.json
    const themeJson = {
      $schema: 'https://schemas.wp.org/trunk/theme.json',
      version: 2,
      settings: {
        appearanceTools: true,
        useRootPaddingAwareAlignments: true,
        layout: {
          contentSize: '1200px',
          wideSize: '1440px',
        },
        color: {
          palette: [
            { slug: 'base', color: compiledTokens.tokens.bg, name: 'Base Background' },
            { slug: 'surface', color: compiledTokens.tokens.surface, name: 'Surface' },
            { slug: 'primary', color: compiledTokens.tokens.accent, name: 'Primary Accent' },
            { slug: 'accent', color: compiledTokens.tokens.accent, name: 'Secondary Accent' },
            { slug: 'text', color: compiledTokens.tokens.text, name: 'Text' },
            { slug: 'muted', color: compiledTokens.tokens.muted, name: 'Muted Text' },
            { slug: 'border', color: compiledTokens.tokens.border, name: 'Border' },
          ],
        },
        typography: {
          fontFamilies: [
            {
              fontFamily: compiledTokens.tokens.fontDisplay,
              name: 'Display',
              slug: 'display',
            },
            {
              fontFamily: compiledTokens.tokens.fontBody,
              name: 'Body',
              slug: 'body',
            },
          ],
        },
      },
      styles: {
        color: {
          background: 'var(--wp--preset--color--base)',
          text: 'var(--wp--preset--color--text)',
        },
        typography: {
          fontFamily: 'var(--wp--preset--font-family--body)',
        },
      },
    };
    zip.file('theme.json', JSON.stringify(themeJson, null, 2));

    // functions.php
    const functionsPhp = `<?php
/**
 * ${themeName} functions and definitions.
 * Generated by Natanel Studio Export Engine V1.
 */

if ( ! function_exists( '${themePrefix}_setup' ) ) {
    function ${themePrefix}_setup() {
        add_theme_support( 'wp-block-styles' );
        add_theme_support( 'editor-styles' );
        add_editor_style( 'style.css' );
        add_editor_style( 'assets/css/theme.css' );
    }
}
add_action( 'after_setup_theme', '${themePrefix}_setup' );

function ${themePrefix}_scripts() {
    wp_enqueue_style( '${safeSlug}-theme', get_template_directory_uri() . '/assets/css/theme.css', array(), '1.0.0' );
    if ( is_rtl() || file_exists( get_template_directory() . '/rtl.css' ) ) {
        wp_enqueue_style( '${safeSlug}-rtl', get_template_directory_uri() . '/rtl.css', array('${safeSlug}-theme'), '1.0.0' );
    }
    wp_enqueue_script( '${safeSlug}-theme', get_template_directory_uri() . '/assets/js/theme.js', array(), '1.0.0', true );
}
add_action( 'wp_enqueue_scripts', '${themePrefix}_scripts' );

function ${themePrefix}_register_patterns() {
    if ( function_exists( 'register_block_pattern_category' ) ) {
        register_block_pattern_category( 'natanel-studio', array( 'label' => __( '${themeName} Patterns', '${safeSlug}' ) ) );
    }
}
add_action( 'init', '${themePrefix}_register_patterns' );
`;
    zip.file('functions.php', functionsPhp);

    // rtl.css (generated when project direction is rtl)
    if (isRtl) {
      const rtlCss = `/*
 * RTL Styles for ${themeName}
 * Generated for Hebrew/RTL direction
 */
html, body {
  direction: rtl;
  text-align: right;
}

.studio-section {
  direction: rtl;
}

.studio-section .grid-split {
  direction: rtl;
}
`;
      zip.file('rtl.css', rtlCss);
    }

    // assets/css/theme.css
    const cssVarsString = Object.entries(compiledTokens.cssVariables)
      .map(([key, val]) => `  ${key}: ${val};`)
      .join('\n');

    const themeCss = `:root {
${cssVarsString}
  --studio-content-width: 1200px;
  --studio-section-space: 80px;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background-color: var(--studio-bg);
  color: var(--studio-text);
  font-family: var(--studio-font-body);
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}

.studio-section {
  width: 100%;
  position: relative;
  background-color: var(--studio-bg);
  color: var(--studio-text);
}

.studio-section a {
  color: inherit;
  text-decoration: none;
}

.studio-section img {
  max-width: 100%;
  height: auto;
  display: block;
}

.grid-split {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 48px;
}

@media (max-width: 768px) {
  .grid-split {
    grid-template-columns: 1fr !important;
    gap: 32px !important;
  }
}

@media (prefers-reduced-motion: reduce) {
  *, ::before, ::after {
    animation-duration: 0.001ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.001ms !important;
    scroll-behavior: auto !important;
  }
}
`;
    zip.file('assets/css/theme.css', themeCss);

    // assets/js/theme.js
    const themeJs = `/**
 * ${themeName} theme script
 * Lightweight, dependency-free vanilla JS
 */
document.addEventListener('DOMContentLoaded', function() {
  // Honor prefers-reduced-motion
  const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  // Handle smooth scroll for internal anchors
  document.querySelectorAll('a[href^="#"]').forEach(function(anchor) {
    anchor.addEventListener('click', function(e) {
      const targetId = this.getAttribute('href').slice(1);
      const targetElement = document.getElementById(targetId);
      if (targetElement) {
        e.preventDefault();
        targetElement.scrollIntoView({ behavior: prefersReducedMotion ? 'auto' : 'smooth' });
      }
    });
  });

  // Handle FAQ accordions
  document.querySelectorAll('.studio-accordion-trigger').forEach(function(button) {
    button.addEventListener('click', function() {
      const expanded = this.getAttribute('aria-expanded') === 'true';
      this.setAttribute('aria-expanded', !expanded);
      const content = this.nextElementSibling;
      if (content) {
        content.hidden = expanded;
      }
    });
  });
});
`;
    zip.file('assets/js/theme.js', themeJs);

    // assets/images/
    const imagesFolder = zip.folder('assets/images');
    for (const asset of processedAssets) {
      imagesFolder?.file(asset.filename, asset.buffer);
    }

    // Render Page Sections and Patterns
    const templatesFolder = zip.folder('templates');
    const partsFolder = zip.folder('parts');
    const patternsFolder = zip.folder('patterns');

    // Identify Home page
    const homePage =
      project.pages.find((p) => p.slug === '/' || p.name.toLowerCase() === 'home') ||
      project.pages[0];

    // Identify navigation and footer from home page if present
    let headerSection: SiteSection | undefined;
    let footerSection: SiteSection | undefined;
    const bodySections: SiteSection[] = [];

    const homeSections = [...(homePage.sections || [])].sort((a, b) => a.order - b.order);
    for (let i = 0; i < homeSections.length; i++) {
      const sec = homeSections[i];
      if (i === 0 && (sec.componentRegistryId.startsWith('nav-') || sec.name.toLowerCase().includes('nav'))) {
        headerSection = sec;
      } else if (
        i === homeSections.length - 1 &&
        (sec.componentRegistryId.startsWith('footer-') || sec.name.toLowerCase().includes('footer'))
      ) {
        footerSection = sec;
      } else {
        bodySections.push(sec);
      }
    }

    // Render header part
    const headerMarkup = headerSection
      ? renderSectionMarkup(headerSection, homePage, project, urlToFilenameMap)
      : `<nav class="studio-section studio-default-nav" style="padding: 20px 24px; border-bottom: 1px solid var(--studio-border); display: flex; justify-content: space-between; align-items: center;"><div style="font-weight: 700; font-size: 18px;">${escapeHtml(themeName)}</div></nav>`;

    partsFolder?.file(
      'header.html',
      `<!-- wp:group {"tagName":"header","className":"studio-header-part","layout":{"type":"constrained"}} -->
<!-- wp:html -->
${headerMarkup}
<!-- /wp:html -->
<!-- /wp:group -->`
    );

    // Render footer part
    const footerMarkup = footerSection
      ? renderSectionMarkup(footerSection, homePage, project, urlToFilenameMap)
      : `<footer class="studio-section studio-default-footer" style="padding: 40px 24px; border-top: 1px solid var(--studio-border); text-align: center; font-size: 13px; color: var(--studio-muted);"><p>&copy; ${new Date().getFullYear()} ${escapeHtml(themeName)}. All rights reserved.</p></footer>`;

    partsFolder?.file(
      'footer.html',
      `<!-- wp:group {"tagName":"footer","className":"studio-footer-part","layout":{"type":"constrained"}} -->
<!-- wp:html -->
${footerMarkup}
<!-- /wp:html -->
<!-- /wp:group -->`
    );

    // Render front-page.html
    const frontBodyMarkup = bodySections
      .map((sec) => {
        const secHtml = renderSectionMarkup(sec, homePage, project, urlToFilenameMap);
        return `<!-- wp:group {"tagName":"section","className":"studio-section studio-section-${sec.id}","layout":{"type":"constrained"}} -->
<!-- wp:html -->
${secHtml}
<!-- /wp:html -->
<!-- /wp:group -->`;
      })
      .join('\n\n');

    const frontPageHtml = `<!-- wp:template-part {"slug":"header","tagName":"header"} /-->

<!-- wp:group {"tagName":"main","layout":{"type":"constrained"}} -->
${frontBodyMarkup}
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->`;

    templatesFolder?.file('front-page.html', frontPageHtml);

    // index.html fallback
    const indexHtml = `<!-- wp:template-part {"slug":"header","tagName":"header"} /-->

<!-- wp:group {"tagName":"main","layout":{"type":"constrained"}} -->
<!-- wp:post-content /-->
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->`;
    templatesFolder?.file('index.html', indexHtml);
    templatesFolder?.file('page.html', indexHtml);

    // Render page-specific templates and patterns
    for (const page of project.pages) {
      const pageSections = [...(page.sections || [])].sort((a, b) => a.order - b.order);
      const pageMarkup = pageSections
        .map((sec) => {
          const secHtml = renderSectionMarkup(sec, page, project, urlToFilenameMap);
          // Also save as Gutenberg Pattern
          const patternSlug = `${safeSlug}-${sec.id}`.toLowerCase().replace(/[^a-z0-9-]+/g, '-');
          const patternPhp = `<?php
/**
 * Title: ${sec.name} (${page.name})
 * Slug: ${safeSlug}/${patternSlug}
 * Categories: natanel-studio
 */
?>
<!-- wp:group {"tagName":"section","className":"studio-section studio-section-${sec.id}","layout":{"type":"constrained"}} -->
<!-- wp:html -->
${secHtml}
<!-- /wp:html -->
<!-- /wp:group -->`;
          patternsFolder?.file(`${patternSlug}.php`, patternPhp);

          return `<!-- wp:group {"tagName":"section","className":"studio-section studio-section-${sec.id}","layout":{"type":"constrained"}} -->
<!-- wp:html -->
${secHtml}
<!-- /wp:html -->
<!-- /wp:group -->`;
        })
        .join('\n\n');

      const cleanSlug = page.slug === '/' ? 'home' : page.slug.replace(/^\/+/, '').replace(/[^a-z0-9-]+/g, '-');
      templatesFolder?.file(
        `page-${cleanSlug}.html`,
        `<!-- wp:template-part {"slug":"header","tagName":"header"} /-->

<!-- wp:group {"tagName":"main","layout":{"type":"constrained"}} -->
${pageMarkup}
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->`
      );
    }

    // manifest.json at root
    zip.file('manifest.json', JSON.stringify(manifest, null, 2));

    // Generate ZIP buffer
    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
    const downloadId = `${project.id}-wordpress-${Date.now()}`;

    const { exportStore } = await import('./exportStore');
    exportStore.set(downloadId, {
      buffer: zipBuffer,
      filename,
      mimeType: 'application/zip',
    });

    return {
      success: true,
      target: 'wordpress',
      filename,
      mimeType: 'application/zip',
      downloadUrl: `/api/export/download/${downloadId}`,
      downloadId,
      generatedAt,
      validation,
      manifest,
      message: 'WordPress block theme generated successfully.',
    };
  }
}

function renderSectionMarkup(
  section: SiteSection,
  page: SitePage,
  project: Project,
  urlToFilenameMap: Map<string, string>
): string {
  const componentDef = componentLookup.get(section.componentRegistryId);
  const Component = getStudioComponent(section.componentRegistryId);

  const resolved = resolveSectionAssets(section, componentDef, project.assets, page.id);
  // Rewrite URLs in resolved assets to point to local assets/images/
  const localizedAssets: Record<string, { url: string; alt: string; aspectRatio?: string }> = {};
  for (const [slot, slotAsset] of Object.entries(resolved.assets)) {
    const filename = urlToFilenameMap.get(slotAsset.url) || 'image.png';
    localizedAssets[slot] = {
      url: `assets/images/${filename}`,
      alt: slotAsset.alt || `${section.name} image`,
      aspectRatio: slotAsset.aspectRatio,
    };
  }

  let rawHtml = '';
  try {
    rawHtml = renderToStaticMarkup(
      React.createElement(Component, {
        content: section.content,
        assets: localizedAssets,
        direction: project.business.direction,
        contentMode: 'production',
      })
    );
  } catch {
    rawHtml = `<div class="studio-fallback-block" style="padding: 40px; text-align: center;"><h3>${escapeHtml(section.name)}</h3></div>`;
  }

  // Rewrite any remaining base64 or absolute URLs
  return rewriteAssetUrlsInHtml(rawHtml, urlToFilenameMap, 'assets/images');
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
