import type { StudioDesignTokens, StudioIndustryPreset } from './types';

export const industryDesignTokenPresets: Record<StudioIndustryPreset, { dark: StudioDesignTokens; light: StudioDesignTokens }> = {
  atelier_luxury: {
    dark: {
      bg: '#121214',
      surface: '#18181b',
      text: '#f4f4f2',
      muted: '#8e8e93',
      accent: '#d4af37',
      border: '#27272a',
      fontDisplay: '"Playfair Display", "Cinzel", Georgia, serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '2px',
      sectionSpace: '112px',
      contentWidth: '1240px',
    },
    light: {
      bg: '#f8f7f4',
      surface: '#ffffff',
      text: '#1a1918',
      muted: '#6e6c68',
      accent: '#96742a',
      border: '#e6e3dc',
      fontDisplay: '"Playfair Display", "Cinzel", Georgia, serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '2px',
      sectionSpace: '112px',
      contentWidth: '1240px',
    },
  },
  beauty_wellness: {
    dark: {
      bg: '#141312',
      surface: '#1c1a18',
      text: '#f7f2ed',
      muted: '#999088',
      accent: '#c49a88',
      border: '#2e2a26',
      fontDisplay: '"Cormorant Garamond", Georgia, serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '10px',
      sectionSpace: '104px',
      contentWidth: '1180px',
    },
    light: {
      bg: '#faf6f0',
      surface: '#ffffff',
      text: '#2b231d',
      muted: '#7a6c62',
      accent: '#a86f5c',
      border: '#ece2d8',
      fontDisplay: '"Cormorant Garamond", Georgia, serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '10px',
      sectionSpace: '104px',
      contentWidth: '1180px',
    },
  },
  contractor: {
    dark: {
      bg: '#121417',
      surface: '#1a1d22',
      text: '#f1f3f5',
      muted: '#878f99',
      accent: '#e67e22',
      border: '#2b3038',
      fontDisplay: '"Chakra Petch", "Barlow", sans-serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '4px',
      sectionSpace: '88px',
      contentWidth: '1200px',
    },
    light: {
      bg: '#f4f6f8',
      surface: '#ffffff',
      text: '#181b1f',
      muted: '#5e6873',
      accent: '#d35400',
      border: '#dbe0e6',
      fontDisplay: '"Chakra Petch", "Barlow", sans-serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '4px',
      sectionSpace: '88px',
      contentWidth: '1200px',
    },
  },
  interior_design: {
    dark: {
      bg: '#161413',
      surface: '#201d1b',
      text: '#f4eee9',
      muted: '#9a9189',
      accent: '#c99368',
      border: '#322d29',
      fontDisplay: '"Italiana", "Playfair Display", serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '0px',
      sectionSpace: '120px',
      contentWidth: '1280px',
    },
    light: {
      bg: '#f5f2ed',
      surface: '#ffffff',
      text: '#231e1a',
      muted: '#786e64',
      accent: '#a06538',
      border: '#e3ddd5',
      fontDisplay: '"Italiana", "Playfair Display", serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '0px',
      sectionSpace: '120px',
      contentWidth: '1280px',
    },
  },
  professional_services: {
    dark: {
      bg: '#0f141c',
      surface: '#161d28',
      text: '#f0f4f8',
      muted: '#828e9e',
      accent: '#3b82f6',
      border: '#232e3d',
      fontDisplay: '"Plus Jakarta Sans", sans-serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '6px',
      sectionSpace: '96px',
      contentWidth: '1160px',
    },
    light: {
      bg: '#f8fafc',
      surface: '#ffffff',
      text: '#0f172a',
      muted: '#64748b',
      accent: '#2563eb',
      border: '#e2e8f0',
      fontDisplay: '"Plus Jakarta Sans", sans-serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '6px',
      sectionSpace: '96px',
      contentWidth: '1160px',
    },
  },
  shopify_beauty: {
    dark: {
      bg: '#131113',
      surface: '#1c191c',
      text: '#f7f1f5',
      muted: '#968c94',
      accent: '#e07a9b',
      border: '#2d272d',
      fontDisplay: '"Tenor Sans", "Playfair Display", serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '8px',
      sectionSpace: '96px',
      contentWidth: '1220px',
    },
    light: {
      bg: '#fdf9fb',
      surface: '#ffffff',
      text: '#241a22',
      muted: '#7d6d7a',
      accent: '#c24b72',
      border: '#f0e3ec',
      fontDisplay: '"Tenor Sans", "Playfair Display", serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '8px',
      sectionSpace: '96px',
      contentWidth: '1220px',
    },
  },
  fitness: {
    dark: {
      bg: '#0d0e10',
      surface: '#15171b',
      text: '#f5f6f8',
      muted: '#848994',
      accent: '#dfff00',
      border: '#24272e',
      fontDisplay: '"Syne", "Barlow", sans-serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '4px',
      sectionSpace: '96px',
      contentWidth: '1200px',
    },
    light: {
      bg: '#f3f4f6',
      surface: '#ffffff',
      text: '#111315',
      muted: '#5a606d',
      accent: '#a8cc00',
      border: '#d7dce2',
      fontDisplay: '"Syne", "Barlow", sans-serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '4px',
      sectionSpace: '96px',
      contentWidth: '1200px',
    },
  },
  real_estate: {
    dark: {
      bg: '#131518',
      surface: '#1b1e23',
      text: '#f2f4f7',
      muted: '#878e99',
      accent: '#c29b68',
      border: '#272c33',
      fontDisplay: '"Cinzel", "Playfair Display", serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '2px',
      sectionSpace: '112px',
      contentWidth: '1260px',
    },
    light: {
      bg: '#f7f6f4',
      surface: '#ffffff',
      text: '#1a1c1e',
      muted: '#6a707a',
      accent: '#9b7645',
      border: '#e1ded9',
      fontDisplay: '"Cinzel", "Playfair Display", serif',
      fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
      radius: '2px',
      sectionSpace: '112px',
      contentWidth: '1260px',
    },
  },
};

export function getDesignTokensForIndustry(
  industry?: string,
  mode: 'dark' | 'light' = 'dark'
): StudioDesignTokens {
  const key = (industry as StudioIndustryPreset) in industryDesignTokenPresets
    ? (industry as StudioIndustryPreset)
    : 'atelier_luxury';

  return industryDesignTokenPresets[key][mode];
}

export function tokensToCssVariables(tokens: StudioDesignTokens): React.CSSProperties {
  return {
    '--studio-bg': tokens.bg,
    '--studio-surface': tokens.surface,
    '--studio-text': tokens.text,
    '--studio-muted': tokens.muted,
    '--studio-accent': tokens.accent,
    '--studio-border': tokens.border,
    '--studio-font-display': tokens.fontDisplay,
    '--studio-font-body': tokens.fontBody,
    '--studio-radius': tokens.radius,
    '--studio-section-space': tokens.sectionSpace,
    '--studio-content-width': tokens.contentWidth,
  } as React.CSSProperties;
}
