export type ComponentCategory =
  | 'navigation'
  | 'hero'
  | 'logos'
  | 'features'
  | 'services'
  | 'gallery'
  | 'portfolio'
  | 'storytelling'
  | 'stats'
  | 'comparison'
  | 'before_after'
  | 'testimonials'
  | 'reviews'
  | 'faq'
  | 'forms'
  | 'cta'
  | 'footer'
  | 'motion'
  | 'ecommerce'
  | 'cro';

export interface ImageRequirement {
  slot: string;
  aspectRatio: string;
  purpose: string;
  required: boolean;
}

export type VerificationStatus = 'untested' | 'manually_verified' | 'automated_verified';

export interface ComponentDefinition {
  id: string;
  name: string;
  category: ComponentCategory;
  description: string;
  source: 'internal' | 'magic-ui' | 'motion-primitives' | 'kokonut-ui' | '21st-dev' | 'custom' | string;
  sourceUrl?: string | null;
  sourceAuthor?: string;
  upstreamComponent?: string | null;
  originalCategory?: string | null;
  transformationNotes?: string;
  version?: string;
  dateImported?: string;
  renderImplementationId?: string;
  supportedProjectTypes?: string[];
  supportedDirections?: ('ltr' | 'rtl')[];
  license: string;
  tags: string[];
  industryFit: string[];
  styleTags: string[];
  conversionPurpose: string[];
  mobileQuality: 1 | 2 | 3 | 4 | 5;
  mobileVerificationStatus?: VerificationStatus;
  rtlReady: boolean;
  rtlVerificationStatus?: VerificationStatus;
  motionLevel: 'none' | 'subtle' | 'moderate' | 'advanced';
  imageRequirements: ImageRequirement[];
  dependencies: string[];
  framework: 'react' | 'liquid' | 'wordpress' | 'platform-neutral';
  codeLocation: string;
  previewImage?: string;
  status: 'candidate' | 'approved' | 'rejected' | 'draft' | 'deprecated';
}

const rawDemoComponents: ComponentDefinition[] = [
  {
    id: 'hero-editorial-split-01',
    name: 'Editorial Split Hero',
    category: 'hero',
    description: 'Large editorial headline with offset media and restrained typography layout.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['editorial', 'premium', 'image-led'],
    industryFit: ['interiors', 'architecture', 'fashion', 'professional-services', 'general'],
    styleTags: ['editorial', 'minimal', 'luxury', 'high-contrast'],
    conversionPurpose: ['positioning', 'primary-cta'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [{ slot: 'hero', aspectRatio: '16:9', purpose: 'Primary brand architectural/product image', required: true }],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/components/registry/demo/EditorialSplitHero.tsx',
    status: 'approved',
  },
  {
    id: 'hero-architectural-panorama-02',
    name: 'Panoramic Cinema Hero',
    category: 'hero',
    description: 'Ultra-wide 21:9 visual banner with grounded typographic hierarchy and direct CTA.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['panoramic', 'cinema', 'immersive'],
    industryFit: ['real-estate', 'architecture', 'hospitality', 'automotive'],
    styleTags: ['cinematic', 'architectural', 'bold'],
    conversionPurpose: ['brand-authority', 'primary-cta'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [{ slot: 'hero-panorama', aspectRatio: '21:9', purpose: 'Panoramic high-res banner', required: true }],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/components/registry/demo/PanoramicHero.tsx',
    status: 'approved',
  },
  {
    id: 'nav-minimal-dock-01',
    name: 'Restrained Studio Nav',
    category: 'navigation',
    description: 'Floating or border-docked minimal navigation with pristine RTL alignment and contact trigger.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['navigation', 'dock', 'sticky'],
    industryFit: ['all', 'creative', 'agency', 'ecommerce'],
    styleTags: ['minimal', 'restrained'],
    conversionPurpose: ['navigation', 'sticky-cta'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/navigation/TransparentRestrainedNav.tsx',
    status: 'approved',
  },
  {
    id: 'cro-trust-strip-01',
    name: 'Conversion Trust Strip',
    category: 'cro',
    description: 'Compact trust row for guarantees, verified outcomes, certifications and client proof.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['trust', 'cro', 'proof'],
    industryFit: ['ecommerce', 'finance', 'consulting', 'medical', 'services'],
    styleTags: ['clean', 'conversion'],
    conversionPurpose: ['trust', 'objection-handling'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/components/registry/demo/TrustStrip.tsx',
    status: 'approved',
  },
  {
    id: 'portfolio-asymmetric-narrative-01',
    name: 'Asymmetric Project Showcase',
    category: 'portfolio',
    description: 'Editorial layout presenting case studies with 4:1 panoramas and detail vignettes.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['case-study', 'editorial', 'gallery'],
    industryFit: ['architecture', 'interiors', 'design', 'luxury'],
    styleTags: ['editorial', 'asymmetric', 'high-craft'],
    conversionPurpose: ['demonstration', 'social-proof'],
    mobileQuality: 4,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [
      { slot: 'project-panorama-1', aspectRatio: '4:1', purpose: 'Ultra-wide project view', required: true },
      { slot: 'project-detail-1', aspectRatio: '16:9', purpose: 'Detail craftsmanship capture', required: true },
    ],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/components/registry/demo/AsymmetricPortfolio.tsx',
    status: 'approved',
  },
  {
    id: 'services-editorial-matrix-01',
    name: 'Typographic Services Matrix',
    category: 'services',
    description: 'Textured typographic service tiers without generic icon boxes or card proliferation.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['services', 'editorial', 'cards-alternative'],
    industryFit: ['consulting', 'law', 'advisory', 'architecture'],
    styleTags: ['typographic', 'restrained', 'sophisticated'],
    conversionPurpose: ['service-clarity', 'inquiry'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/services/TypographicServicesMatrix.tsx',
    status: 'approved',
  },
  {
    id: 'testimonials-portrait-duo-01',
    name: 'Verified Client Portrait Duo',
    category: 'testimonials',
    description: 'High-credibility quotation block pairing authentic 4:5 portrait imagery with quantified impact.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['testimonials', 'credibility', 'portrait'],
    industryFit: ['b2b', 'consulting', 'ecommerce', 'services'],
    styleTags: ['authentic', 'editorial', 'high-trust'],
    conversionPurpose: ['social-proof', 'de-risking'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [{ slot: 'customer-portrait-1', aspectRatio: '4:5', purpose: 'Authentic executive/client portrait', required: true }],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/components/registry/demo/PortraitTestimonials.tsx',
    status: 'approved',
  },
  {
    id: 'forms-high-intent-inquiry-01',
    name: 'High-Intent Frictionless Inquiry',
    category: 'forms',
    description: 'Structured proposal intake form with clear value exchange and native RTL micro-interactions.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['lead-capture', 'inquiry', 'cro'],
    industryFit: ['lead-gen', 'agency', 'contractors', 'luxury-services'],
    styleTags: ['direct', 'tactile', 'minimal'],
    conversionPurpose: ['primary-conversion', 'lead-qualification'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/forms/MultiStepIntakeForm.tsx',
    status: 'approved',
  },
  {
    id: 'cta-contrast-closure-01',
    name: 'High-Contrast Final Action',
    category: 'cta',
    description: 'Full-bleed decisive closing section with stark typography and unmissable call-to-action.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['cta', 'final-push', 'high-contrast'],
    industryFit: ['all'],
    styleTags: ['stark', 'authoritative'],
    conversionPurpose: ['final-conversion'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/components/registry/demo/FinalActionCTA.tsx',
    status: 'approved',
  },
  {
    id: 'footer-architectural-01',
    name: 'Architectural Monolith Footer',
    category: 'footer',
    description: 'Subtle section divider, clean directory layout, legal badges, and localized business presence.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['footer', 'directory', 'legal'],
    industryFit: ['all'],
    styleTags: ['architectural', 'structured'],
    conversionPurpose: ['site-depth', 'trust'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/components/registry/demo/ArchitecturalFooter.tsx',
    status: 'approved',
  },
  {
    id: 'ecommerce-editorial-reel-01',
    name: 'Editorial Product Showcase Reel',
    category: 'ecommerce',
    description: 'Clean product catalog reel with direct Shopify cart integration and tactile image hover.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['shopify', 'catalog', 'ecommerce'],
    industryFit: ['shopify', 'ecommerce', 'fashion', 'homeware'],
    styleTags: ['editorial', 'commerce'],
    conversionPurpose: ['add-to-cart', 'product-discovery'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [{ slot: 'product-feature-1', aspectRatio: '4:5', purpose: 'Product studio shot', required: true }],
    dependencies: [],
    framework: 'liquid',
    codeLocation: 'src/components/registry/demo/ProductShowcaseReel.tsx',
    status: 'approved',
  },
  // --- NATANEL STUDIO EXPANDED PRODUCTION ARSENAL ---
  {
    id: 'nav-editorial-asymmetric-01',
    name: 'Editorial Asymmetric Nav',
    category: 'navigation',
    description: 'Asymmetric typography header pairing location/atelier stamp with balanced action buttons.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['editorial', 'asymmetric', 'navigation'],
    industryFit: ['editorial', 'architecture', 'fashion', 'consulting'],
    styleTags: ['editorial', 'asymmetric', 'typographic'],
    conversionPurpose: ['brand-authority', 'navigation'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/navigation/EditorialAsymmetricNav.tsx',
    status: 'approved',
  },
  {
    id: 'nav-centered-luxury-01',
    name: 'Centered Luxury Monogram Nav',
    category: 'navigation',
    description: 'High-luxury symmetric navigation with centered atelier monogram and flanking menu triggers.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['luxury', 'symmetric', 'monogram'],
    industryFit: ['luxury', 'jewelry', 'beauty', 'atelier'],
    styleTags: ['luxury', 'symmetric', 'restrained'],
    conversionPurpose: ['brand-prestige', 'consultation-cta'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/navigation/CenteredLuxuryNav.tsx',
    status: 'approved',
  },
  {
    id: 'nav-conversion-cta-01',
    name: 'High-Velocity Conversion Nav',
    category: 'navigation',
    description: 'Commercial navigation with prominent phone dispatch number, top emergency banner, and fast estimate button.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['conversion', 'phone-first', 'contractor'],
    industryFit: ['contractors', 'emergency-services', 'home-services', 'medical'],
    styleTags: ['direct', 'conversion', 'high-trust'],
    conversionPurpose: ['instant-call', 'fast-estimate'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/navigation/ConversionCtaNav.tsx',
    status: 'approved',
  },
  {
    id: 'hero-asymmetric-typography-01',
    name: 'Asymmetric Monumental Typography Hero',
    category: 'hero',
    description: 'Monumental typography statement hero stripped of decorative clutter, prioritizing raw verbal clarity.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['typographic', 'asymmetric', 'minimal'],
    industryFit: ['creative', 'design-practice', 'advisory', 'architecture'],
    styleTags: ['typographic', 'asymmetric', 'radical-minimalism'],
    conversionPurpose: ['brand-authority', 'manifesto'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/hero/AsymmetricTypographyHero.tsx',
    status: 'approved',
  },
  {
    id: 'hero-product-spotlight-01',
    name: 'High-Impact Product Commerce Hero',
    category: 'hero',
    description: 'E-commerce hero pairing prominent product photography with ratings, pricing, and instant cart action.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['ecommerce', 'product-spotlight', 'hero'],
    industryFit: ['ecommerce', 'skincare', 'botanicals', 'design-objects'],
    styleTags: ['commerce', 'clean', 'tactile'],
    conversionPurpose: ['add-to-cart', 'direct-purchase'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [{ slot: 'hero-product', aspectRatio: '1:1', purpose: 'Packshot / hero product visual', required: true }],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/hero/ProductCommerceHero.tsx',
    status: 'approved',
  },
  {
    id: 'hero-local-service-01',
    name: 'Local Contractor Conversion Hero',
    category: 'hero',
    description: 'High-converting local service hero with embedded quick-quote intake card and direct phone link.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['contractor', 'intake', 'conversion'],
    industryFit: ['contractors', 'home-services', 'renovation', 'engineering'],
    styleTags: ['conversion', 'high-trust', 'direct'],
    conversionPurpose: ['quote-generation', 'direct-call'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/hero/LocalServiceConversionHero.tsx',
    status: 'approved',
  },
  {
    id: 'hero-minimal-luxury-01',
    name: 'Atelier Minimal Luxury Hero',
    category: 'hero',
    description: 'Restrained centered atelier hero with delicate display typography and private consultation trigger.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['luxury', 'atelier', 'restrained'],
    industryFit: ['luxury', 'jewelry', 'bespoke-tailoring', 'art-consulting'],
    styleTags: ['luxury', 'minimal', 'understated'],
    conversionPurpose: ['private-inquiry', 'exclusivity'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/hero/MinimalLuxuryHero.tsx',
    status: 'approved',
  },
  {
    id: 'cro-emblem-strip-01',
    name: 'Critical Acclaim & Emblem Press Strip',
    category: 'cro',
    description: 'Understated monochrome press and accolade row showcasing institutional recognition and publications.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['press', 'awards', 'proof'],
    industryFit: ['all', 'luxury', 'architecture', 'consulting'],
    styleTags: ['editorial', 'monochrome', 'clean'],
    conversionPurpose: ['social-proof', 'prestige'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/cro/EmblemPressStrip.tsx',
    status: 'approved',
  },
  {
    id: 'cro-metric-proof-01',
    name: 'Quantified Metric Proof Strip',
    category: 'cro',
    description: '4-metric quantified track with prominent numbers and audited delivery precision labels.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['stats', 'metrics', 'proof'],
    industryFit: ['all', 'b2b', 'contractors', 'real-estate'],
    styleTags: ['quantified', 'structured', 'high-trust'],
    conversionPurpose: ['de-risking', 'authority'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/cro/MetricProofStrip.tsx',
    status: 'approved',
  },
  {
    id: 'cro-review-summary-01',
    name: 'Aggregated Review Summary Bar',
    category: 'cro',
    description: 'Consolidated review bar featuring aggregate rating, platform badges, and direct review log link.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['reviews', 'google-reviews', 'trust'],
    industryFit: ['all', 'services', 'ecommerce', 'local-business'],
    styleTags: ['compact', 'social-proof', 'conversion'],
    conversionPurpose: ['instant-credibility'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/cro/ReviewSummaryBar.tsx',
    status: 'approved',
  },
  {
    id: 'cro-guarantee-block-01',
    name: 'Contractual Standard Guarantee Block',
    category: 'cro',
    description: 'Ironclad satisfaction and quality guarantee block with emblem seal, contractual terms, and peace-of-mind checkmarks.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['guarantee', 'warranty', 'cro'],
    industryFit: ['services', 'renovation', 'ecommerce', 'consulting'],
    styleTags: ['guarantee', 'authoritative', 'high-trust'],
    conversionPurpose: ['risk-elimination', 'conversion-close'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/cro/GuaranteeBlock.tsx',
    status: 'approved',
  },
  {
    id: 'services-numbered-index-01',
    name: 'Methodical Numbered Service Index',
    category: 'services',
    description: 'Interactive numbered accordion breakdown with comprehensive scope deliverables.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['services', 'accordion', 'numbered'],
    industryFit: ['architecture', 'engineering', 'creative-agency', 'strategy'],
    styleTags: ['structured', 'accordion', 'architectural'],
    conversionPurpose: ['scope-education', 'demonstration'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/services/EditorialNumberedIndex.tsx',
    status: 'approved',
  },
  {
    id: 'services-process-timeline-01',
    name: 'Structured Milestone Process Timeline',
    category: 'services',
    description: '4-phase sequential project trajectory detailing timelines, deliverables, and quality gates.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['process', 'timeline', 'milestones'],
    industryFit: ['renovation', 'software', 'architecture', 'custom-builds'],
    styleTags: ['process', 'timeline', 'transparent'],
    conversionPurpose: ['expectation-setting', 'trust-building'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/services/ProcessMilestoneTimeline.tsx',
    status: 'approved',
  },
  {
    id: 'services-comparison-table-01',
    name: 'Direct Quality Comparison Table',
    category: 'services',
    description: 'Direct comparison table contrasting Studio standard against ordinary practices across 5 dimensions.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['comparison', 'table', 'differentiation'],
    industryFit: ['all', 'contractors', 'luxury', 'software'],
    styleTags: ['table', 'comparative', 'analytical'],
    conversionPurpose: ['differentiation', 'value-justification'],
    mobileQuality: 4,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/services/ComparisonTable.tsx',
    status: 'approved',
  },
  {
    id: 'portfolio-horizontal-reel-01',
    name: 'Horizontal Kinetic Project Reel',
    category: 'portfolio',
    description: 'Smooth tactile card reel showcasing projects with smooth scrolling controls and categorized metadata.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['portfolio', 'reel', 'horizontal-scroll'],
    industryFit: ['creative', 'architecture', 'fashion', 'hospitality'],
    styleTags: ['kinetic', 'reel', 'immersive'],
    conversionPurpose: ['portfolio-depth', 'discovery'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [{ slot: 'reel-items', aspectRatio: '16:10', purpose: 'Portfolio project cards', required: true }],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/portfolio/HorizontalProjectReel.tsx',
    status: 'approved',
  },
  {
    id: 'storytelling-editorial-narrative-01',
    name: 'Editorial Craft & Thesis Narrative',
    category: 'storytelling',
    description: 'Storytelling chapter pairing studio atmosphere portrait with design thesis, material sourcing, and founder quote.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['storytelling', 'founder', 'thesis'],
    industryFit: ['all', 'luxury', 'atelier', 'craft'],
    styleTags: ['narrative', 'editorial', 'authentic'],
    conversionPurpose: ['brand-affinity', 'emotional-connection'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [{ slot: 'narrative-portrait', aspectRatio: '4:5', purpose: 'Founder or atelier craft capture', required: true }],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/portfolio/EditorialStoryNarrative.tsx',
    status: 'approved',
  },
  {
    id: 'storytelling-sticky-narrative-01',
    name: 'Sticky Split Craft Narrative',
    category: 'storytelling',
    description: 'Sticky left architectural thesis paired with scrolling right craft step breakdowns and photographic proof.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['sticky', 'craft', 'process'],
    industryFit: ['architecture', 'industrial-design', 'luxury-goods'],
    styleTags: ['sticky', 'split', 'editorial'],
    conversionPurpose: ['process-education', 'craft-proof'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [{ slot: 'step-photos', aspectRatio: '16:9', purpose: 'Craft step captures', required: true }],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/portfolio/StickySplitNarrative.tsx',
    status: 'approved',
  },
  {
    id: 'portfolio-before-after-slider-01',
    name: 'Interactive Before/After Transformation Slider',
    category: 'before_after',
    description: 'Interactive touch/pointer comparison slider revealing dramatic architectural metamorphosis with full RTL support.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['before-after', 'interactive', 'comparison'],
    industryFit: ['renovation', 'architecture', 'interiors', 'aesthetics', 'landscaping'],
    styleTags: ['interactive', 'comparative', 'tactile'],
    conversionPurpose: ['visual-proof', 'conversion-catalyst'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [
      { slot: 'before-image', aspectRatio: '16:9', purpose: 'Original pre-renovation capture', required: true },
      { slot: 'after-image', aspectRatio: '16:9', purpose: 'Completed architectural outcome', required: true },
    ],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/portfolio/BeforeAfterSlider.tsx',
    status: 'approved',
  },
  {
    id: 'testimonials-editorial-quote-01',
    name: 'Monumental Editorial Quote',
    category: 'testimonials',
    description: 'Monumental client statement block with authentic provenance and commission context.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['quote', 'editorial', 'prestige'],
    industryFit: ['luxury', 'architecture', 'consulting'],
    styleTags: ['editorial', 'monumental', 'restrained'],
    conversionPurpose: ['prestige-proof'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/testimonials/EditorialQuote.tsx',
    status: 'approved',
  },
  {
    id: 'testimonials-review-carousel-01',
    name: 'Tactile Review Carousel Slider',
    category: 'reviews',
    description: 'Audited client review slider with interactive navigation, star ratings, and location context.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['reviews', 'carousel', 'social-proof'],
    industryFit: ['all', 'contractors', 'services', 'ecommerce'],
    styleTags: ['slider', 'tactile', 'high-trust'],
    conversionPurpose: ['social-proof', 'de-risking'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/testimonials/ReviewCarouselSlider.tsx',
    status: 'approved',
  },
  {
    id: 'testimonials-case-outcome-01',
    name: 'Quantified Case Study Outcome',
    category: 'testimonials',
    description: 'Quantified client outcome card pairing executive client endorsement with measured property appreciation.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['case-study', 'roi', 'quantified'],
    industryFit: ['real-estate', 'investments', 'b2b', 'contractors'],
    styleTags: ['quantified', 'case-study', 'authoritative'],
    conversionPurpose: ['roi-justification', 'de-risking'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [{ slot: 'client-portrait', aspectRatio: '1:1', purpose: 'Executive portrait', required: true }],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/testimonials/CaseStudyOutcome.tsx',
    status: 'approved',
  },
  {
    id: 'forms-multistep-intake-01',
    name: '3-Step Architectural Intake Brief',
    category: 'forms',
    description: 'Methodical 3-stage intake protocol defining project scope, budget envelope, and client details.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['multistep', 'intake', 'lead-qualifier'],
    industryFit: ['architecture', 'luxury-services', 'custom-homes', 'high-end-agency'],
    styleTags: ['multistep', 'structured', 'tactile'],
    conversionPurpose: ['lead-qualification', 'primary-conversion'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/forms/MultiStepIntakeForm.tsx',
    status: 'approved',
  },
  {
    id: 'forms-single-conversion-01',
    name: 'High-Velocity Callback Form',
    category: 'forms',
    description: 'Frictionless single-row contact callback form designed for fast mobile conversion and telephone dispatch.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['callback', 'lead-capture', 'phone'],
    industryFit: ['contractors', 'emergency-services', 'lead-gen', 'consulting'],
    styleTags: ['direct', 'frictionless', 'conversion'],
    conversionPurpose: ['fast-lead', 'phone-capture'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/forms/SingleStepConversionForm.tsx',
    status: 'approved',
  },
  {
    id: 'forms-faq-accordion-01',
    name: 'Clarity & Concerns FAQ Accordion',
    category: 'faq',
    description: 'Structured FAQ accordion resolving key objections around permits, budgets, and warranties.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['faq', 'accordion', 'objection-handling'],
    industryFit: ['all', 'services', 'ecommerce', 'contractors'],
    styleTags: ['accordion', 'clean', 'informative'],
    conversionPurpose: ['objection-handling', 'friction-reduction'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/forms/FaqAccordionSection.tsx',
    status: 'approved',
  },
  {
    id: 'cta-monumental-statement-01',
    name: 'Monumental Architectural Closing Statement',
    category: 'cta',
    description: 'High-contrast closing statement with authoritative typography and dual consultation triggers.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['cta', 'monumental', 'closing'],
    industryFit: ['all', 'luxury', 'architecture', 'corporate'],
    styleTags: ['monumental', 'high-contrast', 'authoritative'],
    conversionPurpose: ['final-conversion', 'closing'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/cta/MonumentalStatementCta.tsx',
    status: 'approved',
  },
  {
    id: 'cta-twotone-urgency-01',
    name: 'Two-Tone Emergency & Dispatch CTA',
    category: 'cta',
    description: 'High-visibility dispatch box pairing direct telephone dialer with online scheduling trigger.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['cta', 'emergency', 'phone'],
    industryFit: ['emergency-services', 'contractors', 'technical-advisory'],
    styleTags: ['direct', 'urgent', 'high-contrast'],
    conversionPurpose: ['immediate-call', 'fast-booking'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/cta/TwoToneUrgencyCta.tsx',
    status: 'approved',
  },
  {
    id: 'cta-direct-consultation-01',
    name: 'Direct Principal WhatsApp & Phone CTA',
    category: 'cta',
    description: 'Personalized invitation to connect directly with the principal architect via WhatsApp, phone, or direct email.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['whatsapp', 'contact', 'consultation'],
    industryFit: ['boutique-studios', 'advisory', 'architecture', 'luxury'],
    styleTags: ['personal', 'accessible', 'direct'],
    conversionPurpose: ['whatsapp-start', 'direct-inquiry'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/cta/DirectConsultationCta.tsx',
    status: 'approved',
  },
  {
    id: 'ecommerce-product-grid-01',
    name: 'Curated 4-Column Product Grid',
    category: 'ecommerce',
    description: 'Clean product catalog grid with instant cart action, ratings, category tags, and responsive layout.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['ecommerce', 'catalog', 'grid'],
    industryFit: ['ecommerce', 'lighting', 'homeware', 'apparel'],
    styleTags: ['catalog', 'clean', 'tactile'],
    conversionPurpose: ['product-discovery', 'add-to-cart'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [{ slot: 'product-grid-images', aspectRatio: '1:1', purpose: 'Product studio shots', required: true }],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/ecommerce/ProductGridCardRow.tsx',
    status: 'approved',
  },
  {
    id: 'ecommerce-product-detail-01',
    name: 'Material Specs & Provenance Accordion',
    category: 'ecommerce',
    description: 'Deep product inspection module detailing materials, stone care protocols, dimensions, and warranty certificates.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['ecommerce', 'specs', 'materials'],
    industryFit: ['ecommerce', 'luxury-goods', 'lighting', 'furniture'],
    styleTags: ['specs', 'accordion', 'informative'],
    conversionPurpose: ['de-risking', 'value-justification'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/ecommerce/ProductDetailAccordion.tsx',
    status: 'approved',
  },
  {
    id: 'ecommerce-cart-drawer-01',
    name: 'Tactile Cart Drawer Summary',
    category: 'ecommerce',
    description: 'Comprehensive cart panel with line-item management, free shipping status, subtotal, and checkout trigger.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['cart', 'drawer', 'checkout'],
    industryFit: ['ecommerce', 'shopify', 'direct-to-consumer'],
    styleTags: ['drawer', 'checkout', 'tactile'],
    conversionPurpose: ['checkout-initiation', 'aov-protection'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/ecommerce/CartDrawerSummary.tsx',
    status: 'approved',
  },
  {
    id: 'footer-editorial-architectural-01',
    name: 'Editorial Architectural Atelier Footer',
    category: 'footer',
    description: 'Architectural studio footer with physical atelier location, professional license stamps, phone, and disciplined directory.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['footer', 'architectural', 'editorial'],
    industryFit: ['architecture', 'luxury', 'advisory', 'consulting'],
    styleTags: ['architectural', 'structured', 'restrained'],
    conversionPurpose: ['trust', 'contact-depth'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/footer/EditorialArchitecturalFooter.tsx',
    status: 'approved',
  },
  {
    id: 'footer-directory-01',
    name: '4-Column Directory & Dispatch Footer',
    category: 'footer',
    description: 'Full-depth directory footer with architectural newsletter subscription, service index, and legal trust badges.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['footer', 'directory', 'newsletter'],
    industryFit: ['all', 'ecommerce', 'corporate', 'contractors'],
    styleTags: ['directory', 'comprehensive', 'clean'],
    conversionPurpose: ['newsletter-lead', 'site-navigation'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/footer/MultiColumnDirectoryFooter.tsx',
    status: 'approved',
  },
  {
    id: 'footer-minimal-legal-01',
    name: 'Minimal Sovereign Legal Footer',
    category: 'footer',
    description: 'Ultra-restrained footer suited for single-page atelier sites, portfolios, and luxury landing pages.',
    source: 'internal',
    license: 'Proprietary Studio',
    tags: ['footer', 'minimal', 'legal'],
    industryFit: ['luxury', 'creative', 'portfolios'],
    styleTags: ['minimal', 'restrained', 'understated'],
    conversionPurpose: ['legal-compliance'],
    mobileQuality: 5,
    rtlReady: true,
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/footer/MinimalLegalFooter.tsx',
    status: 'approved',
  },
  {
    id: 'features-floating-bento-candidate-01',
    name: 'Experimental Floating Grid',
    category: 'features',
    description: 'Candidate component featuring asymmetric feature groupings; pending visual rhythm verification.',
    source: '21st-dev',
    sourceUrl: 'https://21st.dev/community/bento-grid',
    sourceAuthor: 'Community Contributor',
    upstreamComponent: 'BentoGridVariantB',
    originalCategory: 'Grid Layouts',
    transformationNotes: 'Registered external candidate specification. Render implementation pending.',
    version: '0.1.0',
    dateImported: '2026-03-05',
    supportedProjectTypes: ['technology', 'software'],
    supportedDirections: ['ltr'],
    license: 'MIT',
    tags: ['grid', 'experimental', 'candidate'],
    industryFit: ['technology', 'software'],
    styleTags: ['modern', 'experimental'],
    conversionPurpose: ['feature-tour'],
    mobileQuality: 3,
    mobileVerificationStatus: 'untested',
    rtlReady: false,
    rtlVerificationStatus: 'untested',
    motionLevel: 'moderate',
    imageRequirements: [],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/components/registry/candidate/FloatingGrid.tsx',
    status: 'candidate',
  },
  {
    id: 'hero-purple-gradient-rejected-01',
    name: 'Generic SaaS Card Cluster',
    category: 'hero',
    description: 'Rejected cliché design with purple-to-cyan gradient background and excessive floating cards.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio Quality Review',
    transformationNotes: 'Permanently rejected generic AI cliché with purple-to-cyan gradient and cluttered cards.',
    version: '1.0.0',
    dateImported: '2026-02-15',
    supportedProjectTypes: [],
    supportedDirections: ['ltr'],
    license: 'Proprietary Studio',
    tags: ['rejected', 'cliche', 'generic-ai'],
    industryFit: ['none'],
    styleTags: ['glassmorphism', 'purple-gradient'],
    conversionPurpose: ['none'],
    mobileQuality: 2,
    mobileVerificationStatus: 'untested',
    rtlReady: false,
    rtlVerificationStatus: 'untested',
    motionLevel: 'advanced',
    imageRequirements: [],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/components/registry/rejected/GenericSaaS.tsx',
    status: 'rejected',
  },
];

export const demoComponents: ComponentDefinition[] = rawDemoComponents.map((item) => ({
  sourceUrl: item.source === 'internal' ? null : (item.sourceUrl ?? null),
  sourceAuthor: item.sourceAuthor ?? (item.source === 'internal' ? 'Natanel Studio' : 'External Author'),
  upstreamComponent: item.upstreamComponent ?? null,
  originalCategory: item.originalCategory ?? null,
  transformationNotes: item.transformationNotes ?? (item.source === 'internal' ? 'Original Natanel Studio zero-slop component with bidirectional RTL compliance.' : 'External candidate specification.'),
  version: item.version ?? '1.0.0',
  dateImported: item.dateImported ?? '2026-03-01',
  renderImplementationId: item.renderImplementationId ?? (item.status === 'approved' ? item.id : undefined),
  supportedProjectTypes: item.supportedProjectTypes ?? ['custom', 'lead_generation', 'ecommerce', 'portfolio', 'corporate'],
  supportedDirections: item.supportedDirections ?? (item.rtlReady ? ['ltr', 'rtl'] : ['ltr']),
  mobileVerificationStatus: item.mobileVerificationStatus ?? 'untested',
  rtlVerificationStatus: item.rtlVerificationStatus ?? (item.rtlReady ? 'manually_verified' : 'untested'),
  ...item,
}));

