export type ComponentCategory =
  | 'navigation'
  | 'hero'
  | 'logos'
  | 'features'
  | 'services'
  | 'gallery'
  | 'portfolio'
  | 'storytelling'
  | 'stats'
  | 'comparison'
  | 'before_after'
  | 'testimonials'
  | 'reviews'
  | 'faq'
  | 'forms'
  | 'cta'
  | 'footer'
  | 'motion'
  | 'ecommerce'
  | 'cro';

export interface ImageRequirement {
  slot: string;
  aspectRatio: string;
  purpose: string;
  required: boolean;
}

export type VerificationStatus = 'untested' | 'manually_verified' | 'automated_verified';
export type SupportedProjectType = 'business_website' | 'shopify' | 'both';

export interface ComponentDefinition {
  id: string;
  name: string;
  category: ComponentCategory;
  description: string;
  source: 'internal' | 'magic-ui' | 'motion-primitives' | 'kokonut-ui' | '21st-dev' | 'custom' | string;
  sourceUrl?: string | null;
  sourceAuthor?: string;
  upstreamComponent?: string | null;
  originalCategory?: string | null;
  transformationNotes?: string;
  version?: string;
  dateImported?: string;
  renderImplementationId?: string;
  supportedProjectTypes?: SupportedProjectType[];
  supportedDirections?: ('ltr' | 'rtl')[];
  license: string;
  tags: string[];
  industryFit: string[];
  styleTags: string[];
  conversionPurpose: string[];
  mobileQuality: 1 | 2 | 3 | 4 | 5;
  mobileVerificationStatus?: VerificationStatus;
  rtlReady: boolean;
  rtlVerificationStatus?: VerificationStatus;
  motionLevel: 'none' | 'subtle' | 'moderate' | 'advanced';
  imageRequirements: ImageRequirement[];
  dependencies: string[];
  framework: 'react' | 'liquid' | 'wordpress' | 'platform-neutral';
  codeLocation: string;
  previewImage?: string;
  status: 'candidate' | 'approved' | 'rejected' | 'draft' | 'deprecated';
}

const rawDemoComponents: ComponentDefinition[] = [
  // ==========================================
  // NAVIGATION (4)
  // ==========================================
  {
    id: 'nav-minimal-dock-01',
    name: 'Restrained Studio Nav',
    category: 'navigation',
    description: 'Ultra-refined floating navigation bar with tactile status indicator and quick inquiry trigger.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.2.0',
    renderImplementationId: 'nav-minimal-dock-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['nav', 'header', 'minimal', 'floating'],
    industryFit: ['architecture', 'fashion_luxury', 'legal_finance', 'all'],
    styleTags: ['quiet-luxury', 'minimalist', 'high-contrast'],
    conversionPurpose: ['lead_generation'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react', 'motion'],
    framework: 'react',
    codeLocation: 'src/studio-components/navigation/TransparentRestrainedNav.tsx',
    status: 'approved',
  },
  {
    id: 'nav-editorial-asymmetric-01',
    name: 'Editorial Asymmetric Nav',
    category: 'navigation',
    description: 'Off-grid typographic navigation with category index and secondary coordinates.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'nav-editorial-asymmetric-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['nav', 'editorial', 'asymmetric', 'index'],
    industryFit: ['architecture', 'high_end_dining', 'all'],
    styleTags: ['editorial-bold', 'architectural'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 4,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/navigation/EditorialAsymmetricNav.tsx',
    status: 'approved',
  },
  {
    id: 'nav-centered-luxury-01',
    name: 'Centered Luxury Monogram Nav',
    category: 'navigation',
    description: 'Symmetrical luxury masthead with centered atelier emblem and balanced nav links.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'nav-centered-luxury-01',
    supportedProjectTypes: ['business_website', 'shopify', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['nav', 'luxury', 'centered', 'jewelry'],
    industryFit: ['fashion_luxury', 'jewelry', 'all'],
    styleTags: ['quiet-luxury', 'symmetrical'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/navigation/CenteredLuxuryNav.tsx',
    status: 'approved',
  },
  {
    id: 'nav-conversion-cta-01',
    name: 'High-Velocity Conversion Nav',
    category: 'navigation',
    description: 'Direct-response header with persistent phone dialer and booking trigger.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'nav-conversion-cta-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['nav', 'direct-response', 'emergency', 'phone'],
    industryFit: ['contractors_emergency', 'medical_dental', 'all'],
    styleTags: ['technical-clinical', 'direct-response'],
    conversionPurpose: ['direct_booking', 'phone_call'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/navigation/ConversionCtaNav.tsx',
    status: 'approved',
  },

  // ==========================================
  // HERO (6)
  // ==========================================
  {
    id: 'hero-editorial-split-01',
    name: 'Editorial Split Hero',
    category: 'hero',
    description: 'High-contrast typography paired with portrait ratio imagery and disciplined negative space.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.1.0',
    renderImplementationId: 'hero-editorial-split-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['hero', 'split', 'editorial', 'typography'],
    industryFit: ['architecture', 'fashion_luxury', 'high_end_dining', 'all'],
    styleTags: ['quiet-luxury', 'editorial-bold'],
    conversionPurpose: ['brand_authority', 'lead_generation'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [
      { slot: 'hero_primary', aspectRatio: '4:5', purpose: 'Atelier portfolio or portrait highlight', required: true },
    ],
    dependencies: ['lucide-react', 'motion'],
    framework: 'react',
    codeLocation: 'src/studio-components/hero/EditorialSplitHero.tsx',
    status: 'approved',
  },
  {
    id: 'hero-architectural-panorama-02',
    name: 'Panoramic Cinema Hero',
    category: 'hero',
    description: 'Expansive 16:9 full-bleed architectural perspective with understated captioning and floating inquiry trigger.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.2.0',
    renderImplementationId: 'hero-architectural-panorama-02',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['hero', 'panoramic', 'full-width', 'cinema'],
    industryFit: ['architecture', 'high_end_dining', 'all'],
    styleTags: ['quiet-luxury', 'architectural'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [
      { slot: 'panorama_main', aspectRatio: '16:9', purpose: 'Full-bleed atmospheric setting', required: true },
    ],
    dependencies: ['lucide-react', 'motion'],
    framework: 'react',
    codeLocation: 'src/studio-components/hero/CinematicMediaHero.tsx',
    status: 'approved',
  },
  {
    id: 'hero-asymmetric-typography-01',
    name: 'Asymmetric Monumental Typography Hero',
    category: 'hero',
    description: 'Bold editorial typography with asymmetric headline tracking, studio credentials, and direct consultation CTA.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'hero-asymmetric-typography-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['hero', 'typography', 'asymmetric', 'monumental'],
    industryFit: ['architecture', 'legal_finance', 'all'],
    styleTags: ['editorial-bold', 'architectural'],
    conversionPurpose: ['brand_authority', 'lead_generation'],
    mobileQuality: 4,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react', 'motion'],
    framework: 'react',
    codeLocation: 'src/studio-components/hero/AsymmetricTypographyHero.tsx',
    status: 'approved',
  },
  {
    id: 'hero-product-commerce-01',
    name: 'High-Impact Product Commerce Hero',
    category: 'hero',
    description: 'Conversion-focused hero for single hero products with authentic specs, price, and instant add-to-cart.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'hero-product-commerce-01',
    supportedProjectTypes: ['shopify', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['hero', 'ecommerce', 'product', 'conversion'],
    industryFit: ['fashion_luxury', 'all'],
    styleTags: ['quiet-luxury', 'direct-response'],
    conversionPurpose: ['ecommerce_sale'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [
      { slot: 'product_hero', aspectRatio: '4:5', purpose: 'Studio product lighting packshot', required: true },
    ],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/hero/ProductCommerceHero.tsx',
    status: 'approved',
  },
  {
    id: 'hero-local-conversion-01',
    name: 'Local Contractor Conversion Hero',
    category: 'hero',
    description: 'High-trust localized hero with license proof, dispatch radius, and emergency callback inquiry.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'hero-local-conversion-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['hero', 'local-service', 'contractor', 'emergency'],
    industryFit: ['contractors_emergency', 'medical_dental', 'all'],
    styleTags: ['technical-clinical', 'direct-response'],
    conversionPurpose: ['phone_call', 'lead_generation'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/hero/LocalServiceConversionHero.tsx',
    status: 'approved',
  },
  {
    id: 'hero-minimal-luxury-01',
    name: 'Atelier Minimal Luxury Hero',
    category: 'hero',
    description: 'Ultra-restrained luxury hero centering fine typography, discrete status, and subtle image reveal.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'hero-minimal-luxury-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['hero', 'luxury', 'restrained', 'minimal'],
    industryFit: ['fashion_luxury', 'jewelry', 'all'],
    styleTags: ['quiet-luxury'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [
      { slot: 'luxury_hero', aspectRatio: '3:4', purpose: 'Artisan craftsmanship visual', required: true },
    ],
    dependencies: ['lucide-react', 'motion'],
    framework: 'react',
    codeLocation: 'src/studio-components/hero/MinimalLuxuryHero.tsx',
    status: 'approved',
  },

  // ==========================================
  // CRO & SOCIAL PROOF (5)
  // ==========================================
  {
    id: 'cro-trust-strip-01',
    name: 'Critical Acclaim & Emblem Press Strip',
    category: 'cro',
    description: 'Disciplined typographical press and certification strip with verified publication accolades.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'cro-trust-strip-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['proof', 'press', 'emblem', 'trust'],
    industryFit: ['architecture', 'fashion_luxury', 'all'],
    styleTags: ['quiet-luxury', 'minimalist'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/cro/EmblemPressStrip.tsx',
    status: 'approved',
  },
  {
    id: 'cro-metrics-quantified-01',
    name: 'Quantified Metric Proof Strip',
    category: 'cro',
    description: 'Verifiable business outcome metrics displayed with disciplined numbers and precise context.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'cro-metrics-quantified-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['cro', 'metrics', 'proof', 'numbers'],
    industryFit: ['legal_finance', 'architecture', 'all'],
    styleTags: ['editorial-bold', 'architectural'],
    conversionPurpose: ['brand_authority', 'lead_generation'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/cro/MetricProofStrip.tsx',
    status: 'approved',
  },
  {
    id: 'cro-certification-badges-01',
    name: 'Audited Certification & Warranty Badges',
    category: 'cro',
    description: 'Regulatory licenses, safety compliance, and official trade certifications in a clean trust bar.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'cro-certification-badges-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['cro', 'certification', 'license', 'trust'],
    industryFit: ['contractors_emergency', 'medical_dental', 'all'],
    styleTags: ['technical-clinical'],
    conversionPurpose: ['lead_generation', 'direct_booking'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/cro/TrustCertificationStrip.tsx',
    status: 'approved',
  },
  {
    id: 'cro-review-summary-01',
    name: 'Aggregated Review Summary Bar',
    category: 'cro',
    description: 'Independent review aggregation bar showing authentic ratings, platform icons, and verified badge.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'cro-review-summary-01',
    supportedProjectTypes: ['business_website', 'shopify', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['cro', 'reviews', 'rating', 'social-proof'],
    industryFit: ['contractors_emergency', 'medical_dental', 'all'],
    styleTags: ['quiet-luxury', 'technical-clinical'],
    conversionPurpose: ['brand_authority', 'lead_generation'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/cro/ReviewSummaryBar.tsx',
    status: 'approved',
  },
  {
    id: 'cro-guarantee-block-01',
    name: 'Contractual Standard Guarantee Block',
    category: 'cro',
    description: 'Specific written guarantee with terms, response-time commitment, and warranty badge.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'cro-guarantee-block-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['cro', 'guarantee', 'warranty', 'risk-reversal'],
    industryFit: ['contractors_emergency', 'legal_finance', 'all'],
    styleTags: ['editorial-bold'],
    conversionPurpose: ['lead_generation'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/cro/GuaranteeBlock.tsx',
    status: 'approved',
  },

  // ==========================================
  // SERVICES (4)
  // ==========================================
  {
    id: 'services-editorial-matrix-01',
    name: 'Typographic Services Matrix',
    category: 'services',
    description: 'Methodical 3-column index detailing scope of work, methodology, and deliverables.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'services-editorial-matrix-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['services', 'matrix', 'editorial', 'grid'],
    industryFit: ['architecture', 'legal_finance', 'all'],
    styleTags: ['quiet-luxury', 'editorial-bold'],
    conversionPurpose: ['lead_generation'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/services/TypographicServicesMatrix.tsx',
    status: 'approved',
  },
  {
    id: 'services-numbered-index-01',
    name: 'Methodical Numbered Service Index',
    category: 'services',
    description: 'Sequenced editorial list of capabilities with interactive hover preview and scope specs.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'services-numbered-index-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['services', 'numbered', 'index', 'hover'],
    industryFit: ['architecture', 'fashion_luxury', 'all'],
    styleTags: ['quiet-luxury', 'architectural'],
    conversionPurpose: ['lead_generation'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/services/EditorialNumberedIndex.tsx',
    status: 'approved',
  },
  {
    id: 'services-process-timeline-01',
    name: 'Structured Milestone Process Timeline',
    category: 'services',
    description: 'Numbered linear process stages explaining exactly how client engagements unfold from initial intake to sign-off.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'services-process-timeline-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['process', 'timeline', 'milestones', 'workflow'],
    industryFit: ['architecture', 'contractors_emergency', 'legal_finance', 'all'],
    styleTags: ['architectural', 'editorial-bold'],
    conversionPurpose: ['lead_generation', 'brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/services/ProcessMilestoneTimeline.tsx',
    status: 'approved',
  },
  {
    id: 'services-comparison-table-01',
    name: 'Direct Quality Comparison Table',
    category: 'services',
    description: 'Objective comparative matrix contrasting studio standard vs typical market alternatives.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'services-comparison-table-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['comparison', 'table', 'matrix', 'quality'],
    industryFit: ['contractors_emergency', 'medical_dental', 'all'],
    styleTags: ['technical-clinical', 'direct-response'],
    conversionPurpose: ['lead_generation'],
    mobileQuality: 4,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/services/ComparisonTable.tsx',
    status: 'approved',
  },

  // ==========================================
  // PORTFOLIO & STORYTELLING (5)
  // ==========================================
  {
    id: 'portfolio-asymmetric-narrative-01',
    name: 'Asymmetric Project Showcase',
    category: 'portfolio',
    description: 'Curated architectural commission showcase with dual aspect-ratio photography and discipline details.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'portfolio-asymmetric-narrative-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['portfolio', 'asymmetric', 'case-study'],
    industryFit: ['architecture', 'fashion_luxury', 'all'],
    styleTags: ['quiet-luxury', 'architectural'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 4,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [
      { slot: 'project_large', aspectRatio: '16:10', purpose: 'Macro context site photograph', required: true },
      { slot: 'project_detail', aspectRatio: '4:5', purpose: 'Material detail craftsmanship shot', required: true },
    ],
    dependencies: ['lucide-react', 'motion'],
    framework: 'react',
    codeLocation: 'src/studio-components/portfolio/AsymmetricProjectShowcase.tsx',
    status: 'approved',
  },
  {
    id: 'portfolio-horizontal-reel-01',
    name: 'Horizontal Kinetic Project Reel',
    category: 'portfolio',
    description: 'Smooth horizontal gallery showcasing ongoing commissions and visual archive.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'portfolio-horizontal-reel-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['portfolio', 'horizontal', 'reel', 'gallery'],
    industryFit: ['architecture', 'fashion_luxury', 'all'],
    styleTags: ['quiet-luxury'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 4,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'moderate',
    imageRequirements: [
      { slot: 'reel_items', aspectRatio: '3:4', purpose: 'Project card imagery', required: true },
    ],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/portfolio/HorizontalProjectReel.tsx',
    status: 'approved',
  },
  {
    id: 'portfolio-editorial-narrative-01',
    name: 'Editorial Craft & Thesis Narrative',
    category: 'storytelling',
    description: 'Long-form editorial storytelling layout combining manifesto text, atelier photography, and founding principles.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'portfolio-editorial-narrative-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['storytelling', 'narrative', 'editorial', 'craft'],
    industryFit: ['architecture', 'high_end_dining', 'all'],
    styleTags: ['editorial-bold', 'quiet-luxury'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [
      { slot: 'story_atelier', aspectRatio: '4:5', purpose: 'Atelier craftsmanship shot', required: true },
    ],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/portfolio/EditorialStoryNarrative.tsx',
    status: 'approved',
  },
  {
    id: 'portfolio-sticky-split-01',
    name: 'Sticky Split Craft Narrative',
    category: 'storytelling',
    description: 'Sticky left-hand thesis column paired with scrolling visual evidence and annotated milestone captions.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'portfolio-sticky-split-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['storytelling', 'sticky', 'split', 'craft'],
    industryFit: ['architecture', 'fashion_luxury', 'all'],
    styleTags: ['architectural', 'editorial-bold'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 4,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [
      { slot: 'narrative_steps', aspectRatio: '4:3', purpose: 'Sequential craftsmanship steps', required: true },
    ],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/portfolio/StickySplitNarrative.tsx',
    status: 'approved',
  },
  {
    id: 'portfolio-before-after-01',
    name: 'Interactive Before/After Transformation Slider',
    category: 'before_after',
    description: 'Interactive comparison slider demonstrating real site or material transformation.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'portfolio-before-after-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['before-after', 'slider', 'interactive', 'proof'],
    industryFit: ['contractors_emergency', 'architecture', 'all'],
    styleTags: ['architectural', 'technical-clinical'],
    conversionPurpose: ['brand_authority', 'lead_generation'],
    mobileQuality: 4,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [
      { slot: 'before_image', aspectRatio: '16:9', purpose: 'Original state prior to work', required: true },
      { slot: 'after_image', aspectRatio: '16:9', purpose: 'Completed architectural outcome', required: true },
    ],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/portfolio/BeforeAfterSlider.tsx',
    status: 'approved',
  },

  // ==========================================
  // TESTIMONIALS (4)
  // ==========================================
  {
    id: 'testimonials-editorial-quote-01',
    name: 'Monumental Editorial Quote',
    category: 'testimonials',
    description: 'Monumental client statement block with authentic provenance and commission context.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'testimonials-editorial-quote-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['testimonials', 'quote', 'monumental', 'editorial'],
    industryFit: ['architecture', 'legal_finance', 'all'],
    styleTags: ['editorial-bold', 'quiet-luxury'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/testimonials/EditorialQuote.tsx',
    status: 'approved',
  },
  {
    id: 'testimonials-portrait-duo-01',
    name: 'Verified Client Portrait Duo',
    category: 'testimonials',
    description: 'Dual verified testimonial cards with black-and-white portraits, full names, and project context.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'testimonials-portrait-duo-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['testimonials', 'portraits', 'duo', 'verified'],
    industryFit: ['architecture', 'legal_finance', 'all'],
    styleTags: ['quiet-luxury'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [
      { slot: 'client_portrait_1', aspectRatio: '1:1', purpose: 'Client portrait', required: true },
      { slot: 'client_portrait_2', aspectRatio: '1:1', purpose: 'Client portrait', required: true },
    ],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/testimonials/PortraitTestimonialDuo.tsx',
    status: 'approved',
  },
  {
    id: 'testimonials-review-carousel-01',
    name: 'Tactile Review Carousel Slider',
    category: 'reviews',
    description: 'Card-based testimonial slider with verified purchaser badges, dates, and star ratings.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'testimonials-review-carousel-01',
    supportedProjectTypes: ['business_website', 'shopify', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['reviews', 'carousel', 'slider', 'social-proof'],
    industryFit: ['contractors_emergency', 'medical_dental', 'all'],
    styleTags: ['quiet-luxury', 'direct-response'],
    conversionPurpose: ['lead_generation', 'brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'moderate',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/testimonials/ReviewCarouselSlider.tsx',
    status: 'approved',
  },
  {
    id: 'testimonials-case-study-outcome-01',
    name: 'Quantified Case Study Outcome',
    category: 'testimonials',
    description: 'In-depth case study summary with verifiable client outcome metrics, timeline, and lead testimonial.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'testimonials-case-study-outcome-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['testimonials', 'case-study', 'metrics', 'outcomes'],
    industryFit: ['legal_finance', 'architecture', 'all'],
    styleTags: ['architectural', 'editorial-bold'],
    conversionPurpose: ['lead_generation', 'brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/testimonials/CaseStudyOutcome.tsx',
    status: 'approved',
  },

  // ==========================================
  // FORMS & FAQ (3)
  // ==========================================
  {
    id: 'forms-multistep-intake-01',
    name: '3-Step Architectural Intake Brief',
    category: 'forms',
    description: 'Disciplined multi-step consultation brief with project scope categorization and file drop support.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'forms-multistep-intake-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['forms', 'intake', 'multi-step', 'inquiry'],
    industryFit: ['architecture', 'legal_finance', 'all'],
    styleTags: ['quiet-luxury', 'technical-clinical'],
    conversionPurpose: ['lead_generation'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/forms/MultiStepIntakeForm.tsx',
    status: 'approved',
  },
  {
    id: 'forms-single-step-conversion-01',
    name: 'High-Velocity Callback Form',
    category: 'forms',
    description: 'Compact single-step intake for rapid inquiry response and urgent scheduling.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'forms-single-step-conversion-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['forms', 'callback', 'emergency', 'intake'],
    industryFit: ['contractors_emergency', 'medical_dental', 'all'],
    styleTags: ['technical-clinical', 'direct-response'],
    conversionPurpose: ['lead_generation'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/forms/SingleStepConversionForm.tsx',
    status: 'approved',
  },
  {
    id: 'forms-faq-accordion-01',
    name: 'Clarity & Concerns FAQ Accordion',
    category: 'faq',
    description: 'Clean typographic accordion addressing common friction points, pricing transparency, and guarantees.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'forms-faq-accordion-01',
    supportedProjectTypes: ['business_website', 'shopify', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['faq', 'accordion', 'friction-reversal', 'questions'],
    industryFit: ['contractors_emergency', 'legal_finance', 'all'],
    styleTags: ['quiet-luxury'],
    conversionPurpose: ['lead_generation', 'brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/forms/FaqAccordionSection.tsx',
    status: 'approved',
  },

  // ==========================================
  // CTA (3)
  // ==========================================
  {
    id: 'cta-monumental-statement-01',
    name: 'Monumental Architectural Closing Statement',
    category: 'cta',
    description: 'High-contrast full-bleed typographic closing action block with phone and calendar booking options.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'cta-monumental-statement-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['cta', 'monumental', 'contrast', 'closure'],
    industryFit: ['architecture', 'high_end_dining', 'all'],
    styleTags: ['quiet-luxury', 'editorial-bold'],
    conversionPurpose: ['lead_generation', 'direct_booking'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/cta/MonumentalStatementCta.tsx',
    status: 'approved',
  },
  {
    id: 'cta-two-tone-urgency-01',
    name: 'Two-Tone Emergency & Dispatch CTA',
    category: 'cta',
    description: 'High-visibility split banner with live dispatch status, emergency phone trigger, and transparent terms.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'cta-two-tone-urgency-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['cta', 'emergency', 'dispatch', 'urgency'],
    industryFit: ['contractors_emergency', 'medical_dental', 'all'],
    styleTags: ['technical-clinical', 'direct-response'],
    conversionPurpose: ['phone_call', 'lead_generation'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/cta/TwoToneUrgencyCta.tsx',
    status: 'approved',
  },
  {
    id: 'cta-direct-consultation-01',
    name: 'Direct Principal WhatsApp & Phone CTA',
    category: 'cta',
    description: 'Discreet consultation card with direct line to the lead partner or studio principal.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'cta-direct-consultation-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['cta', 'direct', 'whatsapp', 'phone'],
    industryFit: ['legal_finance', 'architecture', 'all'],
    styleTags: ['quiet-luxury'],
    conversionPurpose: ['direct_booking', 'lead_generation'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/cta/DirectConsultationCta.tsx',
    status: 'approved',
  },

  // ==========================================
  // ECOMMERCE (3)
  // ==========================================
  {
    id: 'ecommerce-product-grid-01',
    name: 'Curated 4-Column Product Grid',
    category: 'ecommerce',
    description: 'Editorial merchandise showcase with clean aspect ratio cards, price tags, and quick-view drawer trigger.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'ecommerce-product-grid-01',
    supportedProjectTypes: ['shopify', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['ecommerce', 'grid', 'products', 'merchandise'],
    industryFit: ['fashion_luxury', 'jewelry', 'all'],
    styleTags: ['quiet-luxury'],
    conversionPurpose: ['ecommerce_sale'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [
      { slot: 'product_cards', aspectRatio: '3:4', purpose: 'Studio product cards', required: true },
    ],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/ecommerce/ProductGridCardRow.tsx',
    status: 'approved',
  },
  {
    id: 'ecommerce-detail-accordion-01',
    name: 'Material Specs & Provenance Accordion',
    category: 'ecommerce',
    description: 'High-end ecommerce technical specification block with material origin, dimensions, and care instructions.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'ecommerce-detail-accordion-01',
    supportedProjectTypes: ['shopify', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['ecommerce', 'specs', 'materials', 'accordion'],
    industryFit: ['fashion_luxury', 'jewelry', 'all'],
    styleTags: ['quiet-luxury', 'technical-clinical'],
    conversionPurpose: ['ecommerce_sale'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/ecommerce/ProductDetailAccordion.tsx',
    status: 'approved',
  },
  {
    id: 'ecommerce-cart-drawer-01',
    name: 'Tactile Cart Drawer Summary',
    category: 'ecommerce',
    description: 'High-polish sliding slide-over cart drawer with order items, shipping progress bar, and 1-click checkout.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'ecommerce-cart-drawer-01',
    supportedProjectTypes: ['shopify', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['ecommerce', 'cart', 'drawer', 'checkout'],
    industryFit: ['fashion_luxury', 'all'],
    styleTags: ['quiet-luxury', 'direct-response'],
    conversionPurpose: ['ecommerce_sale'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'moderate',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/ecommerce/CartDrawerSummary.tsx',
    status: 'approved',
  },

  // ==========================================
  // FOOTER (3)
  // ==========================================
  {
    id: 'footer-editorial-architectural-01',
    name: 'Editorial Architectural Atelier Footer',
    category: 'footer',
    description: 'Quiet-luxury footer with typographic masthead, atelier coordinates, copyright, and regulatory disclosures.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'footer-editorial-architectural-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['footer', 'editorial', 'quiet-luxury', 'coordinates'],
    industryFit: ['architecture', 'fashion_luxury', 'all'],
    styleTags: ['quiet-luxury', 'architectural'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/footer/EditorialArchitecturalFooter.tsx',
    status: 'approved',
  },
  {
    id: 'footer-directory-multicolumn-01',
    name: '4-Column Directory & Dispatch Footer',
    category: 'footer',
    description: 'Comprehensive directory footer organizing service lines, emergency coverage areas, and licensing info.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'footer-directory-multicolumn-01',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['footer', 'directory', 'multi-column', 'links'],
    industryFit: ['contractors_emergency', 'legal_finance', 'all'],
    styleTags: ['technical-clinical', 'editorial-bold'],
    conversionPurpose: ['lead_generation', 'brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/footer/MultiColumnDirectoryFooter.tsx',
    status: 'approved',
  },
  {
    id: 'footer-minimal-legal-01',
    name: 'Minimal Sovereign Legal Footer',
    category: 'footer',
    description: 'Ultra-condensed single-line footer for high-focus single-page landing experiences.',
    source: 'internal',
    sourceAuthor: 'Natanel Studio',
    version: '1.0.0',
    renderImplementationId: 'footer-minimal-legal-01',
    supportedProjectTypes: ['business_website', 'shopify', 'both'],
    supportedDirections: ['ltr', 'rtl'],
    license: 'Proprietary Studio',
    tags: ['footer', 'minimal', 'legal', 'condensed'],
    industryFit: ['all'],
    styleTags: ['quiet-luxury', 'minimalist'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 5,
    mobileVerificationStatus: 'untested',
    rtlReady: true,
    rtlVerificationStatus: 'untested',
    motionLevel: 'none',
    imageRequirements: [],
    dependencies: ['lucide-react'],
    framework: 'react',
    codeLocation: 'src/studio-components/footer/MinimalLegalFooter.tsx',
    status: 'approved',
  },

  // ==========================================
  // CANDIDATE & REJECTED SPECIFICATIONS
  // ==========================================
  {
    id: 'features-floating-bento-candidate-01',
    name: 'Kinetic Floating Bento Grid',
    category: 'features',
    description: 'Candidate external bento grid component. Holds candidate status pending review.',
    source: '21st-dev',
    sourceUrl: 'https://21st.dev/community/bento-grid',
    sourceAuthor: 'Community Contributor',
    upstreamComponent: 'bento-grid-v2',
    originalCategory: 'grid',
    transformationNotes: 'Under architectural review for typography compliance and zero-slop constraints.',
    version: '0.9.0',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr'],
    license: 'MIT',
    tags: ['bento', 'features', 'candidate'],
    industryFit: ['all'],
    styleTags: ['technical-clinical'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 3,
    mobileVerificationStatus: 'untested',
    rtlReady: false,
    rtlVerificationStatus: 'untested',
    motionLevel: 'moderate',
    imageRequirements: [],
    dependencies: ['motion'],
    framework: 'react',
    codeLocation: 'src/studio-components/candidate/FloatingGrid.tsx',
    status: 'candidate',
  },
  {
    id: 'nav-floating-pill-candidate-02',
    name: 'Floating Pill Navbar',
    category: 'navigation',
    description: 'External candidate nav. Missing required provenance (sourceUrl/license). Must remain candidate.',
    source: 'magic-ui',
    sourceUrl: null,
    sourceAuthor: undefined,
    version: '0.1.0',
    supportedProjectTypes: ['business_website', 'both'],
    supportedDirections: ['ltr'],
    license: '',
    tags: ['nav', 'candidate', 'incomplete-provenance'],
    industryFit: ['all'],
    styleTags: ['minimalist'],
    conversionPurpose: ['brand_authority'],
    mobileQuality: 3,
    mobileVerificationStatus: 'untested',
    rtlReady: false,
    rtlVerificationStatus: 'untested',
    motionLevel: 'subtle',
    imageRequirements: [],
    dependencies: ['motion'],
    framework: 'react',
    codeLocation: 'src/studio-components/candidate/FloatingPillNav.tsx',
    status: 'candidate',
  },
  {
    id: 'hero-purple-gradient-rejected-01',
    name: 'Generic SaaS Purple Mesh Hero',
    category: 'hero',
    description: 'Rejected: Violates studio anti-slop guidelines (purple glow, arbitrary floating pill, vague claims).',
    source: 'internal',
    sourceAuthor: 'Natanel Studio Quality Review',
    transformationNotes: 'Rejected during design review: contains banned purple-to-blue gradients and low-intent metrics.',
    version: '1.0.0',
    supportedProjectTypes: ['business_website'],
    supportedDirections: ['ltr'],
    license: 'Proprietary Studio',
    tags: ['rejected', 'ai-slop', 'anti-pattern'],
    industryFit: ['all'],
    styleTags: ['glassmorphism'],
    conversionPurpose: ['none'],
    mobileQuality: 2,
    mobileVerificationStatus: 'untested',
    rtlReady: false,
    rtlVerificationStatus: 'untested',
    motionLevel: 'advanced',
    imageRequirements: [],
    dependencies: [],
    framework: 'platform-neutral',
    codeLocation: 'src/studio-components/rejected/GenericSaaS.tsx',
    status: 'rejected',
  },
];

/**
 * Normalizes component definitions without injecting fake defaults:
 * - dateImported is NOT defaulted to fake '2026-03-01'
 * - rtlVerificationStatus is NOT auto-promoted to 'manually_verified'
 * - sourceAuthor does NOT use generic 'External Author'
 * - supportedProjectTypes strictly business_website | shopify | both
 */
export const demoComponents: ComponentDefinition[] = rawDemoComponents.map((item) => ({
  sourceUrl: item.source === 'internal' ? null : (item.sourceUrl ?? null),
  sourceAuthor: item.sourceAuthor ?? (item.source === 'internal' ? 'Natanel Studio' : undefined),
  upstreamComponent: item.upstreamComponent ?? null,
  originalCategory: item.originalCategory ?? null,
  transformationNotes:
    item.transformationNotes ??
    (item.source === 'internal'
      ? 'Original Natanel Studio zero-slop component with bidirectional RTL compliance.'
      : 'External candidate specification.'),
  version: item.version ?? '1.0.0',
  dateImported: item.dateImported,
  renderImplementationId: item.renderImplementationId ?? (item.status === 'approved' ? item.id : undefined),
  supportedProjectTypes: item.supportedProjectTypes ?? ['business_website', 'both'],
  supportedDirections: item.supportedDirections ?? (item.rtlReady ? ['ltr', 'rtl'] : ['ltr']),
  mobileVerificationStatus: item.mobileVerificationStatus ?? 'untested',
  rtlVerificationStatus: item.rtlVerificationStatus ?? 'untested',
  ...item,
}));
